"""Application-wide constants matching roadmap structure."""
from recruitment_ai.config.settings import settings

APP_NAME = settings.APP_NAME
APP_VERSION = settings.APP_VERSION
ENVIRONMENT = settings.ENVIRONMENT
DEBUG = settings.DEBUG

# Brain intent constants
INTENT_CHAT = "CHAT"
INTENT_JOB_PARSER = "JOB_PARSER"
INTENT_JD_GENERATOR = "JD_GENERATOR"
INTENT_RESUME_PARSER = "RESUME_PARSER"
INTENT_RESUME_EDIT = "RESUME_EDIT"
INTENT_RESUME_BUILDER = "RESUME_BUILDER"
INTENT_ATS_SCORE = "ATS_SCORE"
INTENT_JOB_MATCH = "JOB_MATCH"
INTENT_CAREER_ADVICE = "CAREER_ADVICE"
INTENT_SKILL_ASSESSMENT = "SKILL_ASSESSMENT"
INTENT_INTERVIEW_PREP = "INTERVIEW_PREP"
INTENT_CAREER_ROADMAP = "CAREER_ROADMAP"
INTENT_SKILL_GAP = "SKILL_GAP"
INTENT_COVER_LETTER = "COVER_LETTER"
INTENT_RECRUITER = "RECRUITER"
INTENT_RECRUITER_SEARCH = "RECRUITER_SEARCH"
INTENT_RECRUITER_SHORTLIST = "RECRUITER_SHORTLIST"

# User roles
ROLE_CANDIDATE = "candidate"
ROLE_EMPLOYER = "employer"
ROLE_ADMIN = "admin"
ROLE_SYSTEM = "system"

# Provider names
PROVIDER_OLLAMA = "ollama"
PROVIDER_BEDROCK = "bedrock"
