from __future__ import annotations
from datetime import datetime, timezone
from enum import Enum
from typing import Optional, Any
from pydantic import BaseModel, Field


# ── Performance Classification ─────────────────────────────────────────────

class PerformanceClassification(str, Enum):
    HIGH_PERFORMING = "HIGH_PERFORMING"
    LOW_PERFORMING = "LOW_PERFORMING"


class AnalysisStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    WAITING_FOR_DATA = "WAITING_FOR_DATA"


# ── Authoritative Performance Candidate (from Dashboard) ──────────────────

class PerformanceCandidate(BaseModel):
    """
    Authoritative performance candidate provided by the dashboard performance engine.
    The AI service does NOT classify, gate, or rank performance.
    """
    platform: str
    content_id: str
    account_key: str = ""
    performance_level: str  # 'HIGH_PERFORMING' | 'LOW_PERFORMING'
    content_type: str = "Video"
    title: str = ""
    url: Optional[str] = None
    canonical_url: Optional[str] = None
    published_at: Optional[str] = None
    period: str = "30d"
    current_metric: float = 0.0
    baseline_metric: Optional[float] = None
    metric_name: str = "views"
    likes: float = 0.0
    comments: float = 0.0
    peer_explanation: str = ""
    transcript: Optional[str] = None
    transcript_status: Optional[str] = None

    @property
    def effective_url(self) -> Optional[str]:
        raw = (self.canonical_url or self.url or "").strip()
        is_cdn = any(cdn in raw.lower() for cdn in [
            "fbcdn.net", "cdninstagram.com", "akamaihd.net", "fbsbx.com", "cdn.", ".fbcdn."
        ]) or any(raw.lower().endswith(ext) for ext in [".mp4", ".jpg", ".jpeg", ".png", ".webp"])
        if is_cdn or not raw:
            p = (self.platform or "").lower()
            ct = (self.content_type or "").lower()
            cid = self.content_id
            if p == "youtube":
                return f"https://www.youtube.com/shorts/{cid}" if "short" in ct else f"https://www.youtube.com/watch?v={cid}"
            elif p == "instagram":
                return f"https://www.instagram.com/reel/{cid}/" if "reel" in ct else f"https://www.instagram.com/p/{cid}/"
            elif p == "facebook":
                return f"https://www.facebook.com/{cid}"
        return raw or None


class ContentMetadata(BaseModel):
    content_id: str
    title: str
    creator_id: str
    platform: Optional[str] = None
    published_at: Optional[datetime] = None
    content_type: Optional[str] = None
    canonical_url: Optional[str] = None


# ── Data Quality ───────────────────────────────────────────────────────────

class DataQuality(BaseModel):
    baseline_available: bool = True
    metrics_complete: bool = True
    notes: Optional[str] = None


# ── Evidence Package ───────────────────────────────────────────────────────

class EvidencePackage(BaseModel):
    """
    Bounded evidence package constructed strictly from verified candidate data,
    metadata, and transcripts. No second performance classification is performed.
    """
    candidate: PerformanceCandidate
    transcript_excerpt: Optional[str] = None
    regional_signals: Optional[dict] = None
    data_quality: DataQuality = Field(default_factory=DataQuality)

    @property
    def content_metadata(self) -> ContentMetadata:
        return ContentMetadata(
            content_id=self.candidate.content_id,
            title=self.candidate.title,
            creator_id=self.candidate.account_key,
            platform=self.candidate.platform,
            content_type=self.candidate.content_type,
            canonical_url=self.candidate.effective_url,
        )


# ── AI Structured Analysis ─────────────────────────────────────────────────

class EditorialAnalysis(BaseModel):
    """
    Structured editorial insight generated by the LLM based strictly on verified evidence.
    """
    content_intent: str
    observed_signals: list[str]
    possible_contributing_factors: list[str]
    writer_recommendations: list[str]
    keyword_suggestions: list[str] = Field(default_factory=list)
    title_suggestions: list[str] = Field(default_factory=list)
    description_suggestions: list[str] = Field(default_factory=list)
    hashtag_suggestions: list[str] = Field(default_factory=list)
    cross_platform_ideas: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    limitations: list[str] = Field(default_factory=list)
    recommended_action: Optional[str] = None
    publishing_timing: Optional[str] = None


# ── Validation ─────────────────────────────────────────────────────────────

class ValidationResult(BaseModel):
    is_valid: bool
    failures: list[str] = Field(default_factory=list)


# ── Audit ──────────────────────────────────────────────────────────────────

class AuditRecord(BaseModel):
    event_id: str
    content_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    classification: PerformanceClassification
    analysis_status: AnalysisStatus
    provider_used: Optional[str] = None
    validation_passed: Optional[bool] = None
    llm_invoked: bool = False
